name: ${name}
main: ${main}
version: ${version}
author: ${author}
description: ${description}
api-version: ${apiversion}
website: ${website}

depend:
  - kCommon

commands:
  kchat:
    description: Main commmand for kChat
    usage: /kchat reload
    aliases: [kchat, kc]
    permission: system.chat.reload
